[Huggingface](https://huggingface.co/)

In [24]:
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel

In [25]:
sentence = "natural language processing for speech and text data"

In [26]:
model_name = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = TFBertModel.from_pretrained(model_name)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [27]:
input = tokenizer(sentence, return_tensors="tf", padding=True,truncation=True)

In [28]:
input

{'input_ids': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=
array([[ 101, 3019, 2653, 6364, 2005, 4613, 1998, 3793, 2951,  102]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [29]:
outputs = model(input)

In [30]:
last_hidden_states = outputs.last_hidden_state

In [43]:
sentence_embedding = tf.reduce_mean(last_hidden_states, axis=1)
sentence_embedding

<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-1.36805698e-01, -3.52933705e-02, -2.57827997e-01,
        -1.31375939e-01,  2.54073888e-01,  2.49611855e-01,
         1.83284402e-01,  4.92745489e-01, -2.81577170e-01,
        -2.53174245e-01,  1.25042303e-02, -4.31017572e-04,
        -3.11622530e-01, -2.84044985e-02, -2.52227008e-01,
         5.00769794e-01, -1.52671024e-01,  3.58639807e-01,
        -2.23001868e-01,  4.43309605e-01,  1.22332513e-01,
         2.73646601e-02, -1.42800435e-01,  2.39134103e-01,
         6.68085515e-01, -4.28610474e-01, -3.64565194e-01,
         1.40373304e-01, -5.16279459e-01, -4.61827040e-01,
        -2.28030056e-01,  3.62954438e-01, -2.57070661e-01,
        -1.18888699e-01, -5.86144328e-02,  1.36630565e-01,
        -2.60145515e-01, -2.80792326e-01, -2.99018681e-01,
         2.59279430e-01, -8.24888885e-01, -2.83869028e-01,
        -4.05554056e-01,  6.44516721e-02, -1.13581715e-03,
        -1.92688346e-01, -1.82612032e-01, -3.80549440e-03,
      

In [32]:
sentence_embedding.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-1.36805683e-01, -3.52940746e-02, -2.57828325e-01,
        -1.31376341e-01,  2.54073709e-01,  2.49612242e-01,
         1.83284551e-01,  4.92745161e-01, -2.81577021e-01,
        -2.53174424e-01,  1.25033678e-02, -4.30861866e-04,
        -3.11622530e-01, -2.84045693e-02, -2.52227157e-01,
         5.00769973e-01, -1.52670771e-01,  3.58639777e-01,
        -2.23001957e-01,  4.43309456e-01,  1.22332498e-01,
         2.73649152e-02, -1.42800540e-01,  2.39134103e-01,
         6.68086410e-01, -4.28609848e-01, -3.64565670e-01,
         1.40372723e-01, -5.16279161e-01, -4.61826861e-01,
        -2.28029966e-01,  3.62954319e-01, -2.57070482e-01,
        -1.18889019e-01, -5.86144105e-02,  1.36630446e-01,
        -2.60144502e-01, -2.80792832e-01, -2.99019277e-01,
         2.59279132e-01, -8.24888527e-01, -2.83869267e-01,
        -4.05553401e-01,  6.44520372e-02, -1.13583729e-03,
        -1.92688689e-01, 

In [33]:
sentence_embedding.shape

TensorShape([1, 768])

In [34]:
import torch
from transformers import BertModel

In [35]:
model = BertModel.from_pretrained(model_name)

In [36]:
inputs = tokenizer(sentence, return_tensors="pt", padding=True,truncation=True)

In [37]:
with torch.no_grad():
    outputs = model(**inputs)

In [38]:
last_hidden_states = outputs.last_hidden_state

In [39]:
sentence_embedding = torch.mean(last_hidden_states, dim=1)

In [40]:
sentence_embedding.shape

torch.Size([1, 768])

In [41]:
sentence_embedding

tensor([[-1.3681e-01, -3.5293e-02, -2.5783e-01, -1.3138e-01,  2.5407e-01,
          2.4961e-01,  1.8328e-01,  4.9275e-01, -2.8158e-01, -2.5317e-01,
          1.2504e-02, -4.3102e-04, -3.1162e-01, -2.8404e-02, -2.5223e-01,
          5.0077e-01, -1.5267e-01,  3.5864e-01, -2.2300e-01,  4.4331e-01,
          1.2233e-01,  2.7365e-02, -1.4280e-01,  2.3913e-01,  6.6809e-01,
         -4.2861e-01, -3.6457e-01,  1.4037e-01, -5.1628e-01, -4.6183e-01,
         -2.2803e-01,  3.6295e-01, -2.5707e-01, -1.1889e-01, -5.8614e-02,
          1.3663e-01, -2.6015e-01, -2.8079e-01, -2.9902e-01,  2.5928e-01,
         -8.2489e-01, -2.8387e-01, -4.0555e-01,  6.4452e-02, -1.1358e-03,
         -1.9269e-01, -1.8261e-01, -3.8055e-03,  7.7151e-03,  3.0249e-01,
         -7.4040e-01,  2.0622e-01, -1.4026e-01,  2.2627e-01,  9.7100e-02,
          6.4996e-01,  4.4653e-03, -6.6440e-01,  3.3527e-01, -1.6868e-01,
          2.0501e-01, -1.1281e-01, -2.2569e-01, -6.0236e-01,  7.3980e-01,
         -4.1785e-01, -1.2817e-01, -1.